name: Create Cypress report parallel
#on:
  #  push
  #  branches:
  #    - 'master'
  # Add this part if you want to schedule test rerun
  #schedule:
     #- cron: '0 8 * * *' #every day at 8pm - minute hour day mounth year.
on:
  [push]
    #branches:
    #  - 'master'
  #schedule:
    #- cron: '0 5 1-31 * *'     
     
     

jobs:       
  ui-chrome-mobile-tests:
    runs-on: ubuntu-latest
    container: cypress/browsers:node14.17.0-chrome88-ff89
    strategy:
      fail-fast: false
      matrix:
        # run copies of the current job in parallel
        containers: [1, 2, 3, 4]
    continue-on-error: true
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: "UI Tests - Chrome - Mobile"
        uses: cypress-io/github-action@v2
        with:
          config: "viewportWidth=375,viewportHeight=667"
          wait-on-timeout: 120
          browser: chrome
          record: true
          parallel: true
          group: "UI - Chrome - Mobile"
          spec: "integration/UI/*/*.js"
        env:
          CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ github.token }}
        continue-on-error: true
      - name: Save built folders 🆙
        uses: actions/upload-artifact@v2
        with:
          name: built
          path: |
            cypress
            results
            
  ui-windows-tests:
    timeout-minutes: 40
    runs-on: windows-2019
    strategy:
      fail-fast: false
      matrix:
        # run copies of the current job in parallel
        containers: [1, 2]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: "UI Tests - Electron - Windows"
        uses: cypress-io/github-action@v2
        with:
          wait-on-timeout: 120
          record: true
          parallel: true
          group: "UI - Electron - Windows"
          spec: "integration/UI/*.js"
        env:
          CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ github.token }}
      - name: Save built folders 🆙
        uses: actions/upload-artifact@v2
        with:
          name: built
          path: |
            cypress
            results
                      
  merge-and-deploy:
    needs: [ui-chrome-mobile-tests, ui-windows-tests]
    runs-on: ubuntu-latest
    container: cypress/browsers:node14.17.0-chrome88-ff89
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Install a project with a clean slate
        run: |
          npm ci
          $(npm bin)/cypress cache path
          $(npm bin)/cypress cache list
          $(npm bin)/cypress verify
        
      - name: Download built folders ⏬
        uses: actions/download-artifact@v2
        with:
          name: built
        
      - name: Merge test results into one
        run: npm run report:merge
        
      - name: Generate HTML report
        run: npm run report:generate
        
      - name: Deploy report page
        uses: peaceiris/actions-gh-pages@v3
        with:
          GITHUB_TOKEN: ${{ github.token }}
          publish_dir: ./public
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
        